image: ubuntu:bionic

before_script:
  - apt-get update -qq
  - apt-get install -y software-properties-common
  - add-apt-repository ppa:rsjtaylor/cmake-backports
  - apt-get update -qq
  - apt-get install -y build-essential cmake gfortran gcc g++ libhdf5-dev
  - export CC=`which gcc`
  - export CXX=`which g++`
  - export FC=`which gfortran`
  - ulimit -s unlimited

compile_and_test:
  script:
    - mkdir -p build
    - cd build
    - cmake .. && make && ctest --timeout 120 --output-on-failure
  only:
    refs:
      - master
