imgae: gcc
before_script:
  - apt-get update -qq
  - apt-get install -y gfortran cmake
  - apt-get install -y libhdf5-7
  - mkdir -p build

cmake:
  script:
    - cd build && cmake .. && make && ctest --timeout 1 --output-on-failure
