image: ubuntu:bionic

before_script:
  - apt-get update -qq && apt-get install -y cmake gfortran gcc g++ libhdf5-dev
  - export CC=`which gcc`
  - export CXX=`which g++`
  - export FC=`which gfortran`

cmake:
  script:
    - mkdir -p build
    - cd build
    - cmake .. && make && ctest --timeout 10 --output-on-failure
