before_script:
  - apt-get update -qq
  - apt-get install -y gfortran cmake
  - apt-get install -y libhdf5-dev
  - mkdir -p build

cmake:
  script:
    - cd build
    - cmake ..
    - make
    - ctest --timeout 10 --output-on-failure
